### PR TITLE
incremental improvements

### PR DESCRIPTION
**Pull request by WardCunningham**
We detect lineup based race conditions and offer a better error.
image

We correctly overlap fetches by starting request in LINKS and resolving their promise when a deeper level HERE needs the linked page. We see fetch heavy diagrams speed up by 6x.

image

### CODE REVIEW

**Comment by WardCunningham** [comment]
Next up for this pull request: correctly follow collaborative links.

Scan the Journal of the page HERE for alternative sites. Add this to context so that get has fallback addresses should it encounter 404s.

For extra credit, the LINKS keyword could notice when links are within a Reference plugin's markup and add that item's site to the right place in the alternatives.

**Comment by WardCunningham** [comment]
Add FOLD option to WHERE keyword to find links within page folds.

For example, here we select specific links from the Colossal Cave Adventure.

```
    WHERE FOLD from
      LINKS NODE -> HERE
    WHERE FOLD travel
      LINKS HERE -> NODE
```

image

**Comment by WardCunningham** [comment]
We considered using a cmd/alt-s to save svg but found that it couldn't be detected by an element that didn't have focus. From the moment we are using single-click on the diagram background to initiate download so that we can judge the usefulness of the feature. Here we took a snapshot of browsing a famous pattern language and saved it in an Asset page.

http://found.ward.bay.wiki.org/light-on-two-sides.html
image

**Comment by WardCunningham** [comment]
Sequence of probs (last commit) is not yet enough to render this graph correctly when forked to a new location. I'll need help debugging this.

image

**Comment by WardCunningham** [comment]
Promise within promise now working. Still some problem finding the right journal when passing contexts from here to there.

image

**Comment by WardCunningham** [comment]
@nrn found my last bug. I forget to remember the site where I found the page. That can't possibly work. Now we call `polyget` which returns {site, page}.

image

**Comment by WardCunningham** [comment]
The GRAPH keyword looks here for Graph plugins. Nodes and edges found therein are added to the diagram in much the same way as the LINKS keyword.

image

Here is the markup that rendered first left, then right above.
```
DOT strict digraph
  node [style=filled fillcolor=lightblue]
  LINEUP
    HERE
      GRAPH
```

```
DOT digraph
  layout=neato
  node [style=filled fillcolor=palegreen]
  HERE
    WHERE FOLD solid
      GRAPH
    WHERE FOLD broken
      edge [style=dashed len=1.4]
      GRAPH
```

**Comment by WardCunningham** [comment]
Now with undirected edges too.
image

```
DOT graph
  layout=neato
  node [style=filled fillcolor=palegreen]
  HERE
    WHERE FOLD solid
      GRAPH
    WHERE FOLD broken
      edge [style=dashed len=1.4]
      GRAPH
```

**Comment by WardCunningham** [comment]
This code has been stable for 10 days with no specific plans for related improvements. Now would be a good time for a merge and official release.

**Comment by WardCunningham** [comment]
Well, we have another small improvement but this branch is still ready to be merged.

**Comment by paul90** [comment]
There looks to be a problem with `DOT from page-slug`, when the page does not exist in the same wiki as the page with the plugin, but does exist in a wiki in the page's history or in the neighbourhood.

**Comment by WardCunningham** [comment]
The `DOT from page-slug` limitation @paul90 has identified is rooted here:
https://github.com/dobbs/wiki-plugin-graphviz/blob/ward/improve/client/graphviz.js#L23

On this line we anticipate where the page-slug will be found and fail to try alternatives when this assumption proves untrue. A simple solution is to use the `polyget` function that has been developed since the line above was written.

**Comment by WardCunningham** [comment]
Only one of these sites has the section-diagram called for in the `DOT FROM section-diagram` markup. Still both find and run the desired algorithm. Thanks to @paul90 for catching this omission and providing the test case.
image

**Comment by paul90** [comment]
Published as + wiki-plugin-graphviz@0.4.0

**Pull request merged**
